name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Debug File Structure
        run: ls -R

      - name: Upload Files for Deployment
        uses: actions/upload-pages-artifact@v3
        with:
          name: my-artifact  # ✅ Ensure this matches deploy step
          path: .  # ✅ Ensure it includes your `index.html`

      - name: Debug Uploaded Artifacts
        run: |
          echo "Checking available artifacts..."
          gh run list
          gh run view --log
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          artifact_name: my-artifact  # ✅ Ensure name matches upload step
          token: ${{ secrets.GITHUB_TOKEN }}